name: repo2docker CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install repo2docker
        run: |
          python -m pip install --upgrade pip
          python -m pip install jupyter-repo2docker
          # Upstream bug in docker-py not declaring six - will be fixed
          # on next release https://github.com/docker/docker-py/issues/2842
          python -m pip install six
          # Should be fixed once https://github.com/jupyterhub/repo2docker/issues/1063
          # is merged
          python -m pip install chardet

      - name: Build Docker image
        run: jupyter-repo2docker --no-run --debug .
